### PR TITLE
Fix highlight collisions

### LINKED ISSUE #110: cmp integration background highlight issues
My config
```lua
formatting = {
  fields = { "kind", "abbr", "menu" },
  format = function(entry, item)
    item = require("nvim-highlight-colors").format(entry, item)
    -- the item.abbr returns the user's virtual object eg. the square when it's Color entry
    if item.abbr == "" then
      -- I have kind_icons table looks like kind_icons = { Text = "Tt (this is icon)", ...more icons }
      item.kind = string.format("%s", kind_icons[item.menu])
    else
      item.kind = item.abbr
    end
    item.abbr = item.word
    item.kind_hl_group = item.abbr_hl_group or nil
    item.abbr_hl_group = nil
    return item
end,
}
```

The problem I found is the highlight group (nvim-highlight-000000, ...) doesn't link the bg highlight to the current theme highlight (maybe using the Normal group)
and another one is when I have a custom tailwind variable, it doesn't apply eg text-primary

This is the result, some work when you first see it (type the text and it shows) then when scrolling down and scrolling back, the background color turns to the highlight color group instead
image

before select item
image

after select item
image

my config with a custom icon
image

_Originally posted by @nickp-real in https://github.com/brenoprata10/nvim-highlight-colors/issues/109#issuecomment-2198428197_

### PR DESCRIPTION
**Pull request by mehalter**
Fixes #110

Currently the highlight groups for the highlighting in the document collide with the highlight groups set in the `cmp` formatting function. This is totally fine if the user doesn't use the background highlighting but if they do then it will mess up the highlighting on both. This does a few things: 

1. Makes sure the highlight names only collide if they provide the same highlight group `fg` vs `fg-bg`
2. uses `default = true` to make sure that if the highlight group already exists it doesn't get overwritten, this technically will save performance on each display

### CODE REVIEW

**Comment by brenoprata10** [comment]
Hey o/
How is the highlight collision happening if the function implementations is using my plugin name?
https://github.com/brenoprata10/nvim-highlight-colors/blob/0f9852d4b035028b542ab2afee2e8f7e665a1e5b/lua/nvim-highlight-colors/utils.lua#L38

**Comment by mehalter** [comment]
You are colliding with your own plugin 😅 If the highlighting in the document and in the completion menu are different then they step on each other's toes. If I have highlighting in the document that highlights the background of the word then the hlgroup will be setting the color to the background, then in the completion menu it's always set to the foreground. Those highlight groups  end up getting the same name and therefore mess each other up

**Comment by brenoprata10** [comment]
hahahahah makes sense 😆

File: lua/nvim-highlight-colors/utils.lua [hunk 1]
```diff
@@ -49,7 +49,7 @@ end
 ---* `label`: A string representing a template for the color name, likely using placeholders for the theme name. (e.g., '%-%-theme%-primary%-color')
 ---* `color`: A string representing the actual color value in a valid format (e.g., '#0f1219').
 function M.create_highlight(active_buffer_id, ns_id, data, options)
-	local highlight_group = M.create_highlight_name(data.value)
+	local highlight_group
```
Comment (brenoprata10) [inline lua/nvim-highlight-colors/utils.lua:52]: Delete this local var and define it on line 61 and 68 please

**Review by brenoprata10 — CHANGES_REQUESTED** [review]

File: lua/nvim-highlight-colors/utils.lua (hunk 1 above)
Comment (mehalter) [reply lua/nvim-highlight-colors/utils.lua:52]: We need the local variable because it is used later in the code. Therefore deleting that is incorrect

**Comment by mehalter** [comment]
Addressed your comment, let me know if you find anything else in your review :)

File: lua/nvim-highlight-colors/utils.lua [hunk 2]
```diff
@@ -58,14 +58,18 @@ function M.create_highlight(active_buffer_id, ns_id, data, options)
 
 	if options.render == M.render_options.background then
 		local foreground_color = colors.get_foreground_color_from_hex_color(color_value)
+		highlight_group = M.create_highlight_name("fg-bg-" .. data.value)
```
Comment (brenoprata10) [inline lua/nvim-highlight-colors/utils.lua:61]:
```suggestion
		local highlight_group = M.create_highlight_name("fg-bg-" .. data.value)
```

File: lua/nvim-highlight-colors/utils.lua [hunk 3]
```diff
@@ -58,14 +58,18 @@ function M.create_highlight(active_buffer_id, ns_id, data, options)
...
 		pcall(vim.api.nvim_set_hl, 0, highlight_group, {
-            		fg = foreground_color,
-            		bg = color_value
-        	})
+			fg = foreground_color,
+			bg = color_value,
+			default = true,
+		})
 	else
+		highlight_group = M.create_highlight_name("fg-" .. data.value)
```
Comment (brenoprata10) [inline lua/nvim-highlight-colors/utils.lua:68]:
```suggestion
		local highlight_group = M.create_highlight_name("fg-" .. data.value)
```

**Review by brenoprata10 — CHANGES_REQUESTED** [review]
Sorry for not being clear. This is what I meant

**Comment by brenoprata10** [comment]
Ah, nevermind. You're right. I will merge the PR now

**Comment by mehalter** [comment]
Oh, maybe I wasn't clear. Those changes break the code as it removes `highlight_group` from the scope of being outside of those if statements

**Comment by brenoprata10** [comment]
I forgot it was being used in line 81 too :p
